services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: law_firm_backend
    restart: always
    ports:
      - "8000:8000"   # FastAPI expõe na porta 8000
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
      - WHATSAPP_BOT_URL=http://whatsapp_bot:3000
      - FIREBASE_CREDENTIALS=/firebase-key.json
    env_file:
      - .env
    volumes:
      - "C:/Users/Kauane Almeida/Downloads/project-008-orchestration/project/firebase-key.json:/firebase-key.json"
    networks:
      - law_firm_network
    depends_on:
      whatsapp_bot:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  whatsapp_bot:
    build:
      context: .
      dockerfile: Dockerfile.whatsapp
    container_name: law_firm_whatsapp_bot
    restart: always
    ports:
      - "3000:3000"   # Express usa 3000 dentro do container
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FIREBASE_CREDENTIALS=/firebase-key.json
    env_file:
      - .env
    volumes:
      - whatsapp_session:/app/whatsapp_session
      - whatsapp_messages:/app/messages
      - "C:/Users/Kauane Almeida/Downloads/project-008-orchestration/project/firebase-key.json:/firebase-key.json"
    networks:
      - law_firm_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.15'

  frontend:
    image: nginx:alpine
    container_name: law_firm_frontend
    restart: always
    ports:
      - "8080:80"   # Frontend acessível em http://localhost:8080
    volumes:
      - ./frontend:/usr/share/nginx/html:ro   # coloque seu index.html dentro de ./frontend
    networks:
      - law_firm_network
    depends_on:
      - backend

volumes:
  whatsapp_session:
    driver: local
    name: law_firm_whatsapp_session
  whatsapp_messages:
    driver: local
    name: law_firm_whatsapp_messages

networks:
  law_firm_network:
    driver: bridge
    name: law_firm_network
